# React Service YAML
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
  selector:
    app: react
